name: SauceDemo Test Automation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install chromium
        
    - name: Run tests
      run: |
        pytest --alluredir=allure-results
      env:
        STANDARD_USER: standard_user
        STANDARD_PASSWORD: secret_sauce
        LOCKED_OUT_USER: locked_out_user
        LOCKED_OUT_PASSWORD: secret_sauce
        PROBLEM_USER: problem_user
        PROBLEM_PASSWORD: secret_sauce
        BASE_URL: https://www.saucedemo.com/v1
        
    - name: Generate Allure Report
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: allure-results
        allure_report: allure-report
        
    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: |
          allure-report/
          test-results/
          playwright-report/
