name: SauceDemo Test Automation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install --with-deps chromium

    - name: Run Tests
      run: |
        # Run smoke tests
        pytest saucedemo/tests -v -m smoke --headless --alluredir=./allure-results
        # Run regression tests
        pytest saucedemo/tests -v -m regression --headless --alluredir=./allure-results
        # Run security tests
        pytest saucedemo/tests -v -m negative --headless --alluredir=./allure-results
      env:
        STANDARD_USER: standard_user
        STANDARD_PASSWORD: secret_sauce
        LOCKED_OUT_USER: locked_out_user
        LOCKED_OUT_PASSWORD: secret_sauce
        PROBLEM_USER: problem_user
        PROBLEM_PASSWORD: secret_sauce
        BASE_URL: https://www.saucedemo.com/v1
        HEADLESS: true

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          test-results/
          playwright-report/
          pytest-results.xml
          allure-results/
          screenshots/

    - name: Publish Test Report
      if: always()
      uses: dorny/test-reporter@v1
      with:
        name: SauceDemo Tests
        path: pytest-results.xml
        reporter: java-junit