name: SauceDemo Test Automation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-xdist pytest-reportlog
        playwright install --with-deps chromium

    - name: Create directories
      run: |
        mkdir -p test-results
        mkdir -p allure-results
        mkdir -p playwright-report
        mkdir -p screenshots

    - name: Run Tests
      run: |
        # Run smoke tests
        python -m pytest saucedemo/tests -v -m smoke --junitxml=test-results/smoke-results.xml --reportlog=test-results/smoke.log
        # Run regression tests
        python -m pytest saucedemo/tests -v -m regression --junitxml=test-results/regression-results.xml --reportlog=test-results/regression.log
        # Run security tests
        python -m pytest saucedemo/tests -v -m negative --junitxml=test-results/security-results.xml --reportlog=test-results/security.log
      env:
        STANDARD_USER: standard_user
        STANDARD_PASSWORD: secret_sauce
        LOCKED_OUT_USER: locked_out_user
        LOCKED_OUT_PASSWORD: secret_sauce
        PROBLEM_USER: problem_user
        PROBLEM_PASSWORD: secret_sauce
        BASE_URL: https://www.saucedemo.com/v1
        HEADLESS: true
        PYTHONPATH: ${GITHUB_WORKSPACE}

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          test-results/*.xml
          test-results/*.log
          playwright-report/
          allure-results/
          screenshots/

    - name: Publish Test Report
      if: always()
      uses: dorny/test-reporter@v1
      with:
        name: SauceDemo Tests
        path: test-results/*.xml
        reporter: java-junit