name: SauceDemo Test Automation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  test:
    name: SauceDemo Tests
    timeout-minutes: 60
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          xvfb \
          libgbm-dev \
          libxkbcommon-x11-0 \
          libgtk-3-0 \
          libnss3 \
          libxss1 \
          libasound2

    - name: Install Playwright and browsers
      run: |
        python -m playwright install --with-deps chromium

    - name: Create test results directory
      run: |
        mkdir -p test-results
        mkdir -p screenshots

    - name: Run Tests
      run: |
        xvfb-run --auto-servernum -- python -m pytest -v \
          --html=test-results/report.html \
          --junitxml=test-results/junit.xml
      env:
        PYTHONPATH: ${{ github.workspace }}
        HEADLESS: "true"
        BROWSER: "chromium"
        BASE_URL: "https://www.saucedemo.com/v1"
        STANDARD_USER: "standard_user"
        STANDARD_PASSWORD: "secret_sauce"
        LOCKED_OUT_USER: "locked_out_user"
        LOCKED_OUT_PASSWORD: "secret_sauce"
        PROBLEM_USER: "problem_user"
        PROBLEM_PASSWORD: "secret_sauce"
        PLAYWRIGHT_TIMEOUT: "30000"

    - name: Upload Test Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: |
          test-results/
          screenshots/

    - name: Publish Test Results
      if: always()
      uses: dorny/test-reporter@v1
      with:
        name: SauceDemo Tests
        path: "test-results/junit.xml"
        reporter: java-junit
        fail-on-error: false