name: SauceDemo Test Automation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install --with-deps chromium

    - name: Install Allure
      run: |
        curl -o allure-2.13.8.tgz -OL https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.13.8/allure-commandline-2.13.8.tgz
        tar -zxvf allure-2.13.8.tgz -C /tmp
        sudo mv /tmp/allure-2.13.8 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure

    - name: Run Smoke Tests
      run: |
        pytest saucedemo/tests -v -m smoke --headless --alluredir=./allure-results/smoke
      env:
        STANDARD_USER: standard_user
        STANDARD_PASSWORD: secret_sauce
        LOCKED_OUT_USER: locked_out_user
        LOCKED_OUT_PASSWORD: secret_sauce
        PROBLEM_USER: problem_user
        PROBLEM_PASSWORD: secret_sauce
        BASE_URL: https://www.saucedemo.com/v1
        HEADLESS: true

    - name: Run Regression Tests
      run: |
        pytest saucedemo/tests -v -m regression --headless --alluredir=./allure-results/regression
      env:
        STANDARD_USER: standard_user
        STANDARD_PASSWORD: secret_sauce
        LOCKED_OUT_USER: locked_out_user
        LOCKED_OUT_PASSWORD: secret_sauce
        PROBLEM_USER: problem_user
        PROBLEM_PASSWORD: secret_sauce
        BASE_URL: https://www.saucedemo.com/v1
        HEADLESS: true

    - name: Run Security Tests
      run: |
        pytest saucedemo/tests -v -m negative --headless --alluredir=./allure-results/security
      env:
        STANDARD_USER: standard_user
        STANDARD_PASSWORD: secret_sauce
        LOCKED_OUT_USER: locked_out_user
        LOCKED_OUT_PASSWORD: secret_sauce
        PROBLEM_USER: problem_user
        PROBLEM_PASSWORD: secret_sauce
        BASE_URL: https://www.saucedemo.com/v1
        HEADLESS: true

    - name: Generate Allure Report
      if: always()
      run: |
        allure generate allure-results --clean -o allure-report

    - name: Upload Allure Report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: allure-report
        retention-days: 30

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          test-results/
          playwright-report/
          pytest-results.xml
        retention-days: 30

    - name: Upload Failed Test Screenshots
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: failed-test-screenshots
        path: screenshots/
        retention-days: 30

    - name: Publish Test Report
      if: always()
      uses: dorny/test-reporter@v1
      with:
        name: SauceDemo Tests
        path: pytest-results.xml
        reporter: java-junit