name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install --with-deps chromium

    - name: Install Allure
      run: |
        curl -o allure-2.13.8.tgz -OL https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.13.8/allure-commandline-2.13.8.tgz
        tar -zxvf allure-2.13.8.tgz -C /tmp
        sudo mv /tmp/allure-2.13.8 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure

    - name: Run Playwright tests
      run: |
        pytest saucedemo/tests --headless --alluredir=./allure-results -v -n auto

    - name: Generate Allure Report
      if: always()
      run: |
        allure generate allure-results --clean -o allure-report

    - name: Upload Allure Report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: allure-report
        retention-days: 30

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: playwright-results
        path: |
          test-results/
          playwright-report/
        retention-days: 30

    - name: Upload screenshots of failed tests
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: failed-test-screenshots
        path: screenshots/
        retention-days: 30

    - name: Publish Test Report
      if: always()
      uses: dorny/test-reporter@v1
      with:
        name: Playwright Tests
        path: pytest-results.xml
        reporter: java-junit 